/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-17 13:32:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/eGovernment/eGovFrameDev-3.9.0-64bit/farmSpringSM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/farmProject_Spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1690418505182L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	let sessionId = null;\r\n");
      out.write("</script>\r\n");

// 	String name = (String)session.getAttribute("name");
	if(session.getAttribute("id") != null){
		String id = (String)session.getAttribute("id");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	sessionId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("</script>\r\n");

	}
	//정적 파일 경로를 지정하기 위함
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text.html; charset=UTF-8\">\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("<!--     Favicon -->\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@700&family=Open+Sans:wght@400;500;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/lib/lightbox/css/lightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <title>WYC - Turn to farming</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 컨펌 꾸미기 -->\r\n");
      out.write("	<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Spinner Start -->\r\n");
      out.write("    <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"spinner-border text-primary\" role=\"status\" style=\"width: 3rem; height: 3rem;\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5\">\r\n");
      out.write("  <a href=\"index.do\" class=\"navbar-brand d-flex align-items-center\">\r\n");
      out.write("    <h1 class=\"m-0\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/img/logo.png\" style=\"width: 16vw\" /></h1>\r\n");
      out.write("  </a>\r\n");
      out.write("  <button type=\"button\" class=\"navbar-toggler me-0\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("    <div class=\"navbar-nav ms-auto p-4 p-lg-0\">\r\n");
      out.write("      <a href=\"index.do\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("<!--       <a href=\"recomend.do\" class=\"nav-item nav-link\">추천서비스</a> -->\r\n");
      out.write("      <div class=\"nav-item dropdown\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">수익 분석</a>\r\n");
      out.write("        <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("\r\n");
      out.write("          <!-- 비용 조회 메뉴의 세부 요소 추가 -->\r\n");
      out.write("          <div class=\"dropdown\">\r\n");
      out.write("            <a href=\"#\" class=\"dropdown-item dropdown-toggle plusUp\" data-bs-toggle=\"dropdown\">매출 분석</a>\r\n");
      out.write("            <div class=\"dropdown-menu plus\">\r\n");
      out.write("              <a href=\"serviceSales1.do\" class=\"dropdown-item\">농작물 우선 선택</a>\r\n");
      out.write("              <a href=\"serviceSales2.do\" class=\"dropdown-item\">지역  우선 선택</a>\r\n");
      out.write("              <!-- 추가적인 서브 메뉴 항목들... -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a href=\"serviceCost.do\" class=\"dropdown-item\">비용 조회</a>\r\n");
      out.write("          <a href=\"serviceProfit.do\" class=\"dropdown-item\">수익 예측</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a href=\"servicePolicyCheck.do\" class=\"nav-item nav-link\">지원정책</a>\r\n");
      out.write("      <div class=\"nav-item dropdown\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">커뮤니티</a>\r\n");
      out.write("        <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("          <a href=\"festival.do\" class=\"dropdown-item\">지역축제 & 문화행사</a>\r\n");
      out.write("          <a href=\"success.do\" class=\"dropdown-item\">귀농 성공사례</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a href=\"login.do\" class=\"nav-item nav-link loginNav\">로그인</a>\r\n");
      out.write("      <a href=\"joinMember.do\" class=\"nav-item nav-link joinNav\">회원가입</a>\r\n");
      out.write("      <a href=\"logout.do\" class=\"nav-item nav-link logoutNav\" style=\"display: none\">로그아웃</a>\r\n");
      out.write("      <a href=\"mypage.do?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"nav-item nav-link myPageNav\" style=\"display: none\">마이페이지</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- Carousel start -->\r\n");
      out.write("	<div class=\"container-fluid px-0 mb-5\">\r\n");
      out.write("        <div id=\"header-carousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/1.jpg\" alt=\"Image\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-start\">\r\n");
      out.write("                                <div class=\"col-lg-8 text-start\">\r\n");
      out.write("                                    <p class=\"fs-4 text-white\"> 내가 선택한 농작물의 매출을 알아보세요! </p>\r\n");
      out.write("                                    <h1 class=\"display-1 text-white mb-5 animated slideInRight\">Welcome to Jeonnam!</h1>\r\n");
      out.write("                                    <a href=\"serviceSales1.do\" class=\"btn btn-secondary rounded-pill py-3 px-5 animated slideInRight\">농작물 선택</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/2.jpg\" alt=\"Image\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-end\">\r\n");
      out.write("                                <div class=\"col-lg-8 text-end\">\r\n");
      out.write("                                    <p class=\"fs-4 text-white\">원하는 지역을 선택하여 귀농 정보를 알아보세요!</p>\r\n");
      out.write("                                    <h1 class=\"display-1 text-white mb-5 animated slideInRight\">Welcome to  Jeonnam!</h1>\r\n");
      out.write("                                    <a href=\"serviceSales2.do\" class=\"btn btn-secondary rounded-pill py-3 px-5 animated slideInLeft\">지역 선택</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/3.jpg\" alt=\"Image\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-end\">\r\n");
      out.write("                                <div class=\"col-lg-8 text-end\">\r\n");
      out.write("                                    <p class=\"fs-4 text-white\">궁금한 농작물의 비용을 알아보세요!</p>\r\n");
      out.write("                                    <h1 class=\"display-1 text-white mb-5 animated slideInRight\">Welcome to  Jeonnam!</h1>\r\n");
      out.write("                                    <a href=\"serviceCost.do\" class=\"btn btn-secondary rounded-pill py-3 px-5 animated slideInLeft\">비용 분석</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/4.jpg\" alt=\"Image\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-end\">\r\n");
      out.write("                                <div class=\"col-lg-8 text-end\">\r\n");
      out.write("                                    <p class=\"fs-4 text-white\">귀농후 얻게될 수익을 알아보세요!</p>\r\n");
      out.write("                                    <h1 class=\"display-1 text-white mb-5 animated slideInRight\">Welcome to  Jeonnam!</h1>\r\n");
      out.write("                                    <a href=\"serviceProfit.do\" class=\"btn btn-secondary rounded-pill py-3 px-5 animated slideInLeft\">수익 조회</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#header-carousel\"\r\n");
      out.write("                data-bs-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#header-carousel\"\r\n");
      out.write("                data-bs-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Carousel End -->\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<!-- About Start -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row g-5 align-items-end\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"row g-2\">\r\n");
      out.write("                        <div class=\"col-6 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                            <img class=\"img-fluid rounded\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/service-1.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                            <img class=\"img-fluid rounded\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/service-2.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6 wow fadeIn\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                            <img class=\"img-fluid rounded\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/service-3.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6 wow fadeIn\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                            <img class=\"img-fluid rounded\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/service-4.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 wow fadeIn\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <p class=\"section-title bg-white text-start text-primary pe-3\">About Us</p>\r\n");
      out.write("                    <h1 class=\"mb-4\">다양한 귀농정보를 경험해 보세요</h1>\r\n");
      out.write("                    <p class=\"mb-4\">귀농시 수익에 대한 불안정성과 정보 부족으로 고민이신가요?<br>우리 서비스와 함께 고민을 해결해 봅시다!</p>\r\n");
      out.write("                    <div class=\"row g-5 pt-2 mb-5\">\r\n");
      out.write("                        <div class=\"col-sm-6\">\r\n");
      out.write("                            <img class=\"img-fluid mb-4\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/service.png\" alt=\"\">\r\n");
      out.write("                            <h5 class=\"mb-3\">수익분석 서비스</h5>\r\n");
      out.write("                            <span>선호하는 농작물과 선호하는 지역에서 수익 예측 기능 제공</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-6\">\r\n");
      out.write("                            <img class=\"img-fluid mb-4\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/award.png\" alt=\"\">\r\n");
      out.write("                            <h5 class=\"mb-3\">정부지원 정책들</h5>\r\n");
      out.write("                            <span>전라남도 22개 지역별 정부지원 정책 확인 기능 제공</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"btn btn-secondary rounded-pill py-3 px-5\" href=\"serviceSales1.do\">Explore More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- About End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- Main Service Start -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"text-center mx-auto pb-4 wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 500px;\">\r\n");
      out.write("                <p class=\"section-title bg-white text-center text-primary px-3\">Main Services</p>\r\n");
      out.write("                <h1 class=\"mb-5\">주요 기능</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gy-5 gx-4\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 pt-5 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"service-item d-flex h-100\">\r\n");
      out.write("                        <div class=\"service-img\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/index_sales.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text p-5 pt-0\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <img class=\"img-fluid rounded-circle\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/index_sales.jpg\" alt=\"\" style=\"height: -webkit-fill-available;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5 class=\"mb-3\">매출 확인</h4>\r\n");
      out.write("                            <p class=\"mb-4\">당신이 선호하는 지역과 농작물의 매출을 확인해보세요.</p>\r\n");
      out.write("                            <a class=\"btn btn-square rounded-circle\" href=\"serviceSales1.do\"><i class=\"bi bi-chevron-double-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 pt-5 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"service-item d-flex h-100\">\r\n");
      out.write("                        <div class=\"service-img\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/index_cost.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text p-5 pt-0\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <img class=\"img-fluid rounded-circle\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/index_cost.jpg\" alt=\"\" style=\"height: -webkit-fill-available;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5 class=\"mb-3\">비용 확인</h4>\r\n");
      out.write("                            <p class=\"mb-4\">농작물별 소요비용과 정부 정책 지원을 검색 한 소요비용을 분석해 보세요.</p>\r\n");
      out.write("                            <a class=\"btn btn-square rounded-circle\" href=\"serviceCost.do\"><i class=\"bi bi-chevron-double-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 pt-5 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"service-item d-flex h-100\">\r\n");
      out.write("                        <div class=\"service-img\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/index_profit.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text p-5 pt-0\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <img class=\"img-fluid rounded-circle\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/index_profit.jpg\" alt=\"\" style=\"height: -webkit-fill-available;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5 class=\"mb-3\">수익 확인</h5>\r\n");
      out.write("                            <p class=\"mb-4\">농작물 매출과 귀농시 필요한 초기 비용, 운영 비용을 종합한 수익을 확인해보세요.</p>\r\n");
      out.write("                            <a class=\"btn btn-square rounded-circle\" href=\"serviceProfit.do\"><i class=\"bi bi-chevron-double-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 pt-5 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"service-item d-flex h-100\">\r\n");
      out.write("                        <div class=\"service-img\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/index_policy.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text p-5 pt-0\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <img class=\"img-fluid rounded-circle\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/index_policy.jpg\" alt=\"\" style=\"height: -webkit-fill-available;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5 class=\"mb-3\">정부지원 정책 확인</h5>\r\n");
      out.write("                            <p class=\"mb-4\">지자체별 정부지원 정책을 확인해보세요.</p>\r\n");
      out.write("                            <a class=\"btn btn-square rounded-circle\" href=\"servicePolicyCheck.do\"><i class=\"bi bi-chevron-double-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Main Service End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Community Service_1 Start -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"text-center mx-auto pb-4 wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 500px;\">\r\n");
      out.write("                <p class=\"section-title bg-white text-center text-primary px-3\">Community Services</p>\r\n");
      out.write("                <h1 class=\"mb-5\">커뮤니티 서비스</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gy-5 gx-4\">\r\n");
      out.write("                <div class=\"col-lg-6 pt-5 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"service-item d-flex h-100\">\r\n");
      out.write("                        <div class=\"service-img\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/community-2.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text p-5 pt-0\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <img class=\"img-fluid rounded-circle\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/community-2.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5 class=\"mb-3\">지역축제 & 문화행사</h5>\r\n");
      out.write("                            <p class=\"mb-4\">전라남도에서 제공하는 다양한 농촌 체험 활동 및 문화행사를 즐겨보세요.</p>\r\n");
      out.write("                            <a class=\"btn btn-square rounded-circle\" href=\"festival.do\"><i class=\"bi bi-chevron-double-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 pt-5 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"service-item d-flex h-100\">\r\n");
      out.write("                        <div class=\"service-img\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/community-3.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text p-5 pt-0\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <img class=\"img-fluid rounded-circle\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/community-3.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5 class=\"mb-3\">귀농 성공사례</h5>\r\n");
      out.write("                            <p class=\"mb-4\">당신의 성공 노하우를 다른 사람들과 공유해보세요.</p>\r\n");
      out.write("                            <a class=\"btn btn-square rounded-circle\" href=\"success.do\"><i class=\"bi bi-chevron-double-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Community Service_1 End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Event Service Start -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 500px;\">\r\n");
      out.write("                <p class=\"section-title bg-white text-center text-primary px-3\">Local Festival & Cultural Event</p>\r\n");
      out.write("                <h1 class=\"mb-5\">전라남도에서 제공하는<br>다양한 농촌 체험 활동을<br>즐겨보세요.</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gx-4\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <a href=\"https://ggeutdeul.modoo.at/\">\r\n");
      out.write("                                <img class=\"img-event\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/event-1.jpeg\" alt=\"\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"https://ggeutdeul.modoo.at/\">섬진강 끝들마을</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <a href=\"http://www.xn--hq1b37i55ll3as6p.kr/\">\r\n");
      out.write("                                <img class=\"img-event\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/event-2.jpg\" alt=\"\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"http://www.xn--hq1b37i55ll3as6p.kr/\">완도 신학마을</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <a href=\"https://ecowg.modoo.at/\">\r\n");
      out.write("                                <img class=\"img-event\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/event-3.jpeg\" alt=\"\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"https://ecowg.modoo.at/\">에코왕곡마을</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <a href=\"http://echovill.com/\">\r\n");
      out.write("                                <img class=\"img-event\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/event-4.jpg\" alt=\"\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"http://echovill.com/\">메아리 창조마을</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Event Service End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Festival Service Start -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 500px;\">\r\n");
      out.write("                <p class=\"section-title bg-white text-center text-primary px-3\">Local Festival & Cultural Event</p>\r\n");
      out.write("                <h1 class=\"mb-5\">전라남도에서 제공하는 <br>문화행사를 경험해보세요.</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gx-4\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <a href=\"https://www.gokseong.go.kr/tour/festivity\">\r\n");
      out.write("                                <img class=\"img-festival\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/festival-1.jpg\" alt=\"\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"https://www.gokseong.go.kr/tour/festivity\">곡성 세계 장미축제</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">23.05.20 ~ 23.05.29</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <a href=\"http://www.bspdanoje.co.kr/\">\r\n");
      out.write("                                <img class=\"img-festival\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/festival-2.png\" alt=\"\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"http://www.bspdanoje.co.kr/\">영광 법성포 단오제</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">23.06.22 ~ 23.06.25</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <a href=\"https://www.gokseong.go.kr/tour/festivity/icecream\">\r\n");
      out.write("                                <img class=\"img-festival\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/festival-3.jpg\" alt=\"\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"https://www.gokseong.go.kr/tour/festivity/icecream\">곡성 아이스크림 페스티벌</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">23.07.14 ~ 23.07.16</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <a href=\"https://festival.jangheung.go.kr/festival\">\r\n");
      out.write("                                <img class=\"img-festival\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/festival-4.jpg\" alt=\"\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"https://festival.jangheung.go.kr/festival\">정남진 장흥 물축제</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">23.07.29 ~ 23.08.06</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Festival Service End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark footer mt-5 py-5 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Our Office</h5>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt me-3\"></i>서울시 마포구 신촌로 104 4층, 5층<br>그린컴퓨터</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-phone-alt me-3\"></i>02-715-2111</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-envelope me-3\"></i>http://sinchon.greenart.co.kr/</p>\r\n");
      out.write("                    <div class=\"d-flex pt-3\">\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"https://github.com/sungminw/WYC_profit_Prediction.git\"><i class=\"fab fa-github\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Quick Links</h5>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"serviceSales1.do\">매출 확인(농작물우선)</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"serviceSales2.do\">매출 확인(지역우선)</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"serviceCost.do\">비용 조회</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"serviceProfit.do\">수익 확인</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"servicePolicyCheck.do\">정부지원 정책들</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"festival.do\">지역축제 & 문화행사</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Business Hours</h5>\r\n");
      out.write("                    <p class=\"mb-1\">Monday - Friday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">09:30 am - 06:20 pm</h6>\r\n");
      out.write("                    <p class=\"mb-1\">Saturday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">Closed</h6>\r\n");
      out.write("                    <p class=\"mb-1\">Sunday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">Closed</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Copyright Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-secondary text-body copyright py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-start mb-3 mb-md-0\">\r\n");
      out.write("                    &copy; <a class=\"fw-semi-bold\" href=\"#\">WYC - Turning to Farm</a>, All Right Reserved.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-end\">\r\n");
      out.write("                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". Thank you for your support. ***/-->\r\n");
      out.write("                    Designed By <a class=\"fw-semi-bold\" href=\"https://github.com/sungminw/WYC_profit_Prediction.git\">Team WYC</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/parallax/parallax.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/lightbox/js/lightbox.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/js/userMgmt.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
