/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-21 14:19:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class serviceSales1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/eGovernment/eGovFrameDev-3.9.0-64bit/farmSpringSM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/farmProject_Spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1690418505182L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	let sessionId = null;\r\n");
      out.write("</script>\r\n");

// 	String name = (String)session.getAttribute("name");
	if(session.getAttribute("id") != null){
		String id = (String)session.getAttribute("id");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	sessionId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("</script>\r\n");

	}
	//정적 파일 경로를 지정하기 위함
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("    <title>WYC - Turn to farming</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/img/favicon.ico\" rel=\"icon\">  \r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@700&family=Open+Sans:wght@400;500;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/lib/lightbox/css/lightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/css/revenueChart.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!--     <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/lightbox/js/chart.js\"></script> -->\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/css/serviceSales1.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print( contextPath );
      out.write("/resources/css/header.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("	<!-- 컨펌 꾸미기 -->\r\n");
      out.write("	<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Spinner Start -->\r\n");
      out.write("    <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"spinner-border text-primary\" role=\"status\" style=\"width: 3rem; height: 3rem;\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5\">\r\n");
      out.write("  <a href=\"index.do\" class=\"navbar-brand d-flex align-items-center\">\r\n");
      out.write("    <h1 class=\"m-0\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/img/logo.png\" style=\"width: 16vw\" /></h1>\r\n");
      out.write("  </a>\r\n");
      out.write("  <button type=\"button\" class=\"navbar-toggler me-0\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("    <div class=\"navbar-nav ms-auto p-4 p-lg-0\">\r\n");
      out.write("      <a href=\"index.do\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("<!--       <a href=\"recomend.do\" class=\"nav-item nav-link\">추천서비스</a> -->\r\n");
      out.write("      <div class=\"nav-item dropdown\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">수익 분석</a>\r\n");
      out.write("        <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("\r\n");
      out.write("          <!-- 비용 조회 메뉴의 세부 요소 추가 -->\r\n");
      out.write("          <div class=\"dropdown\">\r\n");
      out.write("            <a href=\"#\" class=\"dropdown-item dropdown-toggle plusUp\" data-bs-toggle=\"dropdown\">매출 분석</a>\r\n");
      out.write("            <div class=\"dropdown-menu plus\">\r\n");
      out.write("              <a href=\"serviceSales1.do\" class=\"dropdown-item\">농작물 우선 선택</a>\r\n");
      out.write("              <a href=\"serviceSales2.do\" class=\"dropdown-item\">지역  우선 선택</a>\r\n");
      out.write("              <!-- 추가적인 서브 메뉴 항목들... -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a href=\"serviceCost.do\" class=\"dropdown-item\">비용 조회</a>\r\n");
      out.write("          <a href=\"serviceProfit.do\" class=\"dropdown-item\">수익 예측</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a href=\"servicePolicyCheck.do\" class=\"nav-item nav-link\">지원정책</a>\r\n");
      out.write("      <div class=\"nav-item dropdown\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">커뮤니티</a>\r\n");
      out.write("        <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("          <a href=\"festival.do\" class=\"dropdown-item\">지역축제 & 문화행사</a>\r\n");
      out.write("          <a href=\"success.do\" class=\"dropdown-item\">귀농 성공사례</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a href=\"login.do\" class=\"nav-item nav-link loginNav\">로그인</a>\r\n");
      out.write("      <a href=\"joinMember.do\" class=\"nav-item nav-link joinNav\">회원가입</a>\r\n");
      out.write("      <a href=\"logout.do\" class=\"nav-item nav-link logoutNav\" style=\"display: none\">로그아웃</a>\r\n");
      out.write("      <a href=\"mypage.do?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"nav-item nav-link myPageNav\" style=\"display: none\">마이페이지</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Header Start -->\r\n");
      out.write("    <div class=\"container-fluid header_img py-5 mb-5\" data-wow-delay=\"0.1s\">\r\n");
      out.write("      <div class=\"container text-center py-5\">\r\n");
      out.write("        <h1 class=\"display-3 text-white mb-4 slideInDown\">매출확인(농작물 우선)</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Page Header End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Service Start -->\r\n");
      out.write("    <form  action=\"serviceCostGo.do\" method=\"post\" name=\"formR1\">\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"text-center mx-auto pb-4 wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 500px;\">\r\n");
      out.write("                <p class=\"section-title bg-white text-center text-primary px-3\">매출 확인</p>\r\n");
      out.write("                <h1 class=\"mb-5\">선호하는 농작물의<br>재배가능지역과 매출을<br>확인해보세요.</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row gy-5 gx-3 inner_content\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-5 pt-3 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"service-item d-flex flex-column h-60\">                       \r\n");
      out.write("                <div class=\"tableTitle\">추천 농작물 리스트</div> \r\n");
      out.write("                \r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("               	\r\n");
      out.write("               	\r\n");
      out.write("                	</div> \r\n");
      out.write("                </div>\r\n");
      out.write("                  \r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 pt-3 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"service-item d-block h-100\">\r\n");
      out.write("                <table class=\"table table-bordered table-hover table-primary\" id=\"myTable\">\r\n");
      out.write("              <thead class=\"thead-dark text-center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th class=\"tableTitle\" width=\"60%\">재배 가능 지역</th>                  \r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody class=\"text-center\" id=\"area\">\r\n");
      out.write("<!--               	재배 가능 지역 테이블 생성                          -->\r\n");
      out.write("	\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("                </div>  \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-5 col-md-9 pt-3 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                  <div class=\"service-item h-100 d-block\">\r\n");
      out.write("              <div class=\"page\">    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("              </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("                </div>\r\n");
      out.write("<!--               </div> -->\r\n");
      out.write("<!--             </div>      -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 경매 단가 그래프 모달창 Start-->\r\n");
      out.write("<div class=\"modal fade bs-example-modal-lg\" id=\"hPrice_draw\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">        \r\n");
      out.write("        <h6 class=\"modal-title\" id=\"myModalLabel\">경매 단가</h6>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-default btn-sm\" data-dismiss=\"modal\">X</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"container-xxl\">\r\n");
      out.write("              <div class=\"text-center mx-auto wow fadeInUp\" style=\"visibility: none;\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                </div>             \r\n");
      out.write("<!--               농작물 매출                          -->\r\n");
      out.write("              <div class=\"col-md-12 col-sm-12 col-xs-12\" id=\"\">\r\n");
      out.write("                <canvas id=\"chart_price\" class=\"chart_price\"></canvas>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("              <div class=\"hPrice_element\">※ 경매단가 분석은 10a(300평)기준이며 최근 5년간의 농수산물유통정보의 도매 가격 데이터를 기준으로 제공 합니다.</div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("<!-- 경매 단가 그래프 모달창 End-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 생산량 그래프 모달창 Start-->\r\n");
      out.write("<div class=\"modal fade bs-example-modal-lg\" id=\"yield_draw\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">        \r\n");
      out.write("        <h6 class=\"modal-title\" id=\"myModalLabel\">생산량</h6>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-default btn-sm\" data-dismiss=\"modal\">X</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"container-xxl\">\r\n");
      out.write("              <div class=\"text-center mx-auto wow fadeInUp\" style=\"visibility: none;\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                </div>             \r\n");
      out.write("<!--               농작물 매출                          -->\r\n");
      out.write("              <div class=\"col-md-12 col-sm-12 col-xs-12\" id=\"\">\r\n");
      out.write("                <canvas id=\"chart_yield\" class=\"chart_yield\"></canvas>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("              <div class=\"yield_element\">※ 생산량 분석은 10a(300평)기준이며 최근 5년간의 통계청의 생산량 데이터를 기준으로 제공 합니다.</div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("<!-- 생산량 그래프 모달창 End-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Large modal -->\r\n");
      out.write("    <div class=\"row no-gutter\">\r\n");
      out.write("      <div id=\"total_sales\" class=\"border_default mt-5 gutter_0\">\r\n");
      out.write("        <div class=\"total_sales_inner\">\r\n");
      out.write("          <div class=\"modal-button\">\r\n");
      out.write("            <button type=\"button\" id=\"total_sales_chart\" data-toggle=\"modal\" data-target=\"#myModal\">매출 확인</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"\">\r\n");
      out.write("<!-- 			<input type=\"hidden\" class=\"wycId\" name=\"wycId\" value=\"testId\"> -->\r\n");
      out.write("<!-- 			<input type=\"hidden\" name=\"selectCrop\"> -->\r\n");
      out.write("<!--          	<input type=\"hidden\" name=\"selectArea\"> -->\r\n");
      out.write("<!-- 			<input type=\"hidden\" class=\"selectCropKor\" name=\"selectCropKor\" value=\"\"> -->\r\n");
      out.write("			<input type=\"hidden\" class=\"areaEng\" name=\"areaEng\" value=\"\">\r\n");
      out.write("         	<input type=\"hidden\" class=\"salesResult\" name=\"salesResult\" value=\"\">\r\n");
      out.write("            <button type=\"button\" id=\"total_sales_submit\">비용 분석</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <!-- 07.12수정함 -->\r\n");
      out.write("      <!-- offset-lg-4 col-lg-2 offset-md-4 col-md-2 -->\r\n");
      out.write("      <!-- col-lg-2 col-md-4 col-sm-6 col-xs-12 -->\r\n");
      out.write("      <!-- <button type=\"button\" class=\"btn btn-primary btn-revenue modal-button\" data-toggle=\"modal\" data-target=\".bs-example-modal-lg\">매출 확인</button> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 여기부터 주석 해제 -->\r\n");
      out.write("<div class=\"modal fade bs-example-modal-lg\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">        \r\n");
      out.write("        <h6 class=\"modal-title\" id=\"myModalLabel\">매출 분석</h6>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-default btn-sm\" data-dismiss=\"modal\">X</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"container-xxl\">\r\n");
      out.write("              <div class=\"text-center mx-auto wow fadeInUp\" style=\"visibility: none;\" data-wow-delay=\"0.3s\">\r\n");
      out.write("<!--                   <p class=\"section-title bg-white text-center text-primary px-3\">매출 분석</p> -->\r\n");
      out.write("                  <div class=\"cost_title\"><span class=\"cost_sigungu\"></span><span> </span><span class=\"cost_crop\"></span>의 내년 예상 매출은 <span class=\"total_cost\"></span>원 입니다</div>\r\n");
      out.write("                </div>             \r\n");
      out.write("<!--               농작물 매출                          -->\r\n");
      out.write("           	  <div class=\"row col-lg-12 col-sm-12 col-md-12 col-xs-12\" id=\"chartContainer\">\r\n");
      out.write("                 <canvas class=\"\" id=\"mychart\"></canvas>              \r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("				<div class=\"sales_element\">※ 매출 분석은 10a(300평)기준이며 분석 요소는 온도, 강수량, 일조시간, 일사량, 생산비용, 경작면적, 생산량, 상등품 도매가격, 유통 비율, GDP 을 분석하여 도출해낸 매출 금액 입니다.</div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("<!--     </div> -->\r\n");
      out.write("<!--     </div> -->\r\n");
      out.write("      \r\n");
      out.write("<!--     </div> -->\r\n");
      out.write("<!--   </div> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  <!-- Community Service End -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark footer mt-5 py-5 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Our Office</h5>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt me-3\"></i>서울시 마포구 신촌로 104 4층, 5층<br>그린컴퓨터</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-phone-alt me-3\"></i>02-715-2111</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-envelope me-3\"></i>http://sinchon.greenart.co.kr/</p>\r\n");
      out.write("                    <div class=\"d-flex pt-3\">\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"https://github.com/Sanghokim91/WYC\"><i class=\"fab fa-github\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Quick Links</h5>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"serviceSales1.do\">매출 확인(농작물우선)</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"serviceSales2.do\">매출 확인(지역우선)</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"serviceCost.do\">비용 조회</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"serviceProfit.do\">수익 확인</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"servicePolicyCheck.do\">정부지원 정책들</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"festival.do\">지역축제 & 문화행사</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Business Hours</h5>\r\n");
      out.write("                    <p class=\"mb-1\">Monday - Friday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">09:30 am - 06:20 pm</h6>\r\n");
      out.write("                    <p class=\"mb-1\">Saturday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">Closed</h6>\r\n");
      out.write("                    <p class=\"mb-1\">Sunday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">Closed</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Copyright Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-secondary text-body copyright py-4\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 text-center text-md-start mb-3 mb-md-0\">\r\n");
      out.write("                  &copy; <a class=\"fw-semi-bold\" href=\"#\">WYC - Turning to Farm</a>, All Right Reserved.\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6 text-center text-md-end\">\r\n");
      out.write("                  <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". Thank you for your support. ***/-->\r\n");
      out.write("                  Designed By <a class=\"fw-semi-bold\" href=\"https://github.com/sungminw/WYC_profit_Prediction.git\">Team WYC</a>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/parallax/parallax.min.js\"></script>       \r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/lib/lightbox/js/lightbox.js\"></script>   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/js/serviceSales1.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/js/userMgmt.js\"></script>\r\n");
      out.write("<!--     <script src=\"");
      out.print( contextPath );
      out.write("/resources/js/revenueChart.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/serviceSales1.jsp(141,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/serviceSales1.jsp(141,16) '${cropList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cropList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/serviceSales1.jsp(141,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("crop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                	<div class=\"form-check py-1\">\r\n");
            out.write("                  		<input class=\"form-check-input btn-crop\" type=\"radio\" name=\"flexRadioDefault\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${crop.cropEng}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  		<label class=\"form-check-label\" for=\"flexRadioDefault1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${crop.cropName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</label>  \r\n");
            out.write("                	</div>\r\n");
            out.write("               	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
